using System;

public class SpecialProduct{

    public static void Main (string[] args) {

        string ids = "KGTMEPNQGDXBWQZQ PAKONFLCBGQDUZIG HESGJHHRZLPYFAOD PSCKWKJTLNRUKEIH UWCELSKZRVRNROYG FEWRPYGKAXHTLRYY FBJQOSBWGXNHULVR YCNWGFPXAEAIWAUQ TFIVSAKWMXUBPNLJ BWQTGSFCAZVCCYOK JHPJBWDAJIEJSKTZ QOCEVEZIPTXRDGWA HVGFJUVYVAKQIXMB WNNUBDKXPZRNVQGO EJCYSHMLVFFGDBXW ODQQQHNYMUKXZVRX IQJCLTYWNZFHBXVA PKVDARGMBUJKWKNG HISBEQSYVFWKMSXT DUXTOAMVKVEHVYRB NEJTSACYIUBKDIHM VIHFOKMEDRYSPATX GTFMVKBSLOKDXKSQ FQOJLFYRECUHBXDF CFOVKMSBXHPAOWOS AMKHSEBZPRGYPWPC FUTCNCUHXSDGYOUL DOLWDFZPTDKHUVYA CJEOAHYVQGKMXAUD TAFCXGETDYTUJLPJ ARMKIVEFKDHWKGMX FTIQBAEVMGNUSLZW FYKTCUVDRFZGSHIF SVUHPUKMYTRAJVVL BLQNXKTTCIUJOOWO ZTWJBLROTATGEPNM TMWOSVFLKIRBAEFH GHJHFPDKOHMVZAUB HTCVUEQGHQYJKQWL LBJNQDWVRAJJPMPX CKLWPNDAHICVSGCJ HVXNSTGPAMAOKDRA OORUVZHYQGKOFLPT IHRINXEFEUYJAWTI GOESBKYBBJNPLITV CQVAYKISVEZOPTVL WTNTOVCAGXHPBTUK HDQHKMYXVHQICSFO JOMBSGKIYRUTQBDB GBDWIISECOAKZUNR";
        string[] lines = ids.Split(' ');

        foreach (string line in lines) {

            

        }
    }
}



